### ISSUE TITLE
get classifier failed

### ISSUE THREAD

**Issue by xjt717394** [xushilin1/RAP-SAM#2]
Hello!
when using the following command to get the classifier:
PYTHONPATH='.' python tools/gen_cls.py configs/rap_sam/rap_sam_convl_12e_adaptor.py
there is a error occured:
ImportError: Failed to import seg.datasets.concat_dataset in configs/rap_sam\..\_base_/datasets/coco_panoptic_video_yt19_sam.py, line 5 for cannot import name 'TrackDataSample' from 'mmdet.structures' (E:\Ana
conda3\envs\IndustryAI_3.10\lib\site-packages\mmdet\structures\__init__.py)
how can I fix the bug or you can send me a classifer to my email!
Many thanks!

**Comment by xushilin1** [comment]
Sorry for the error. I will fix the bug later, and you can download the file here. [ckpt](https://1drv.ms/u/c/12a1b84edebf20f7/EVjJu546FCtAko-aqlsb11IBPMKIIuIrm8blwpP1sDyD6w?e=LvALSA)

**Comment by xjt717394** [comment]
Hello!
I also wonder if you have a plan to develop a python inference interface for our custom use like SAM

**Comment by Masrur02** [comment]
ImportError: Failed to import seg.datasets.concat_dataset in configs/rap_sam/../_base_/datasets/coco_panoptic_video_yt19_sam.py, line 5 for cannot import name 'TrackDataSample' from 'mmdet.structures' (/home/soicroot/miniconda3/envs/rap/lib/python3.8/site-packages/mmdet/structures/__init__.py)


I am also getting this error, is there any solution for it?
