### ISSUE TITLE
Why the fps of Mask2Former in table.3 different from the one listed in Mask2Former?

### ISSUE THREAD

**Issue by shuimushan** [xushilin1/RAP-SAM#3]
![Screenshot from 2024-02-17 14-15-15](https://github.com/xushilin1/RAP-SAM/assets/61351203/1f00a2f2-d0e3-4360-adbe-4ffa7852d4c7)
![Screenshot from 2024-02-17 14-15-25](https://github.com/xushilin1/RAP-SAM/assets/61351203/7f1ea6c0-abbd-4be8-a623-85085401fb9b)

Mask2Former tests its fps on R50 to be 9.7, while you get 26.6. What makes the difference?

**Comment by xushilin1** [comment]
Hi, Thanks for your interest in our work.
We use a `lite neck` instead of `MSDeformAttnPixelDecoder` to satisfy real-time settings, and we test all the fps using A100 gpu.
