### ISSUE TITLE
video demo 

### ISSUE THREAD

**Issue by Ahmed471996** [xushilin1/RAP-SAM#7]
can we run the demo on a video?

**Comment by xushilin1** [comment]
Thanks for your attention. I will provide specific implementation methods later.

**Comment by Ahmed471996** [comment]
any update soon?

**Comment by xushilin1** [comment]
I'm sorry for not getting back to you sooner. 
You can first try our evaluation scripts for videos like this.
```
 ./tools/dist_test.sh configs/rap_sam/eval_rap_sam_yt19.py $CKPT $NUM_GPUS
```
I will provide a more simple video demo and visualization tools later.
